[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
